export  const dataSiswaKelolosan = [
  {
    nama:'Nurinta Altaf Fathiya',
    asalSekolah:'SMA Angkasa 1',
    ptn:'ITB',
    jurusan:'FMIPA-IPA',
  },
  {
    nama:'Najma Audrey Melodia',
    asalSekolah:'SMAN 52 JKT',
    ptn:'ITB',
    jurusan:'Sekolah Bisnis Manajemen',
  },
  {
    nama:'Nashwa Tabina Widodo',
    asalSekolah:'SMAN 12 JKT',
    ptn:'ITB',
    jurusan:'FSRD',
  },
  {
    nama:'Adrian Daniel Pangaribuan',
    asalSekolah:'SMAN 12 JKT',
    ptn:'ITB',
    jurusan:'FTI',
  },
  {
    nama:'Muhammad Nauval Naeem',
    asalSekolah:'SMAN 30 JKT',
    ptn:'ITB',
    jurusan:'FMIPA-IPA',
  },
  {
    nama:'Azzahra Hasfa Julia',
    asalSekolah:'SMAN 110 JKT',
    ptn:'ITB',
    jurusan:'Sekolah Ilmu Tek.Hayati (R)',
  },
  {
    nama:'Dzaki Fachri Rusadhi',
    asalSekolah:'SMAN 77 JKT',
    ptn:'ITB',
    jurusan:'FITB',
  },
  {
    nama:'Indah Aila Aslah',
    asalSekolah:'SMAN 77 JKT',
    ptn:'ITB',
    jurusan:'Sekolah Ilmu Tek.Hayati (R)',
  },
  {
    nama:'Cavella Nayla',
    asalSekolah:'SMAN 12 JKT',
    ptn:'UI',
    jurusan:'T.Metalurgi',
  },
  {
    nama:'Andi Martina',
    asalSekolah:'SMAN 12 JKT',
    ptn:'UI',
    jurusan:'Keperawatan',
  },
  {
    nama:'Nayla Azzahra',
    asalSekolah:'SMAN 13 JKT',
    ptn:'UI',
    jurusan:'Ilmu Hukum',
  },
  {
    nama:'Nailah Muazarah',
    asalSekolah:'SMAN 13 JKT',
    ptn:'UI',
    jurusan:'Kesejahteraan Sosial',
  },
  {
    nama:'Fadillah Agustin',
    asalSekolah:'SMAN 13 JKT',
    ptn:'UI',
    jurusan:'Administrasi Negara',
  },
  {
    nama:'Desita Putri Ardianti',
    asalSekolah:'SMAN 13 JKT',
    ptn:'UI',
    jurusan:'Kimia',
  },
  {
    nama:'Wildan Fachrain Prathama',
    asalSekolah:'SMAN 13 JKT',
    ptn:'UI',
    jurusan:'T.Sipil',
  },
  {
    nama:'Andin Tri Herian',
    asalSekolah:'SMAN 1 JKT',
    ptn:'UI',
    jurusan:'Keperawatan',
  },
  {
    nama:'Safitri Az Zahra',
    asalSekolah:'SMAN 1 JKT',
    ptn:'UI',
    jurusan:'Akutansi',
  },
  {
    nama:'Naisylla Aprillya Yanuar',
    asalSekolah:'SMAN 1 JKT',
    ptn:'UI',
    jurusan:'Kesejahteraan Sosial',
  },
  {
    nama:'Nabilla Aprillya Yanuar',
    asalSekolah:'SMAN 1 JKT',
    ptn:'UI',
    jurusan:'Sastra Inggris',
  },
  {
    nama:'Thifalia Raudina Mahardya',
    asalSekolah:'SMAN 71 JKT',
    ptn:'UI',
    jurusan:'Arsitektur',
  },
  {
    nama:'Nakita Arani',
    asalSekolah:'SMAN 71 JKT',
    ptn:'UI',
    jurusan:'Ilmu Komunikasi',
  },
  {
    nama:'Eliora Pindan Angga',
    asalSekolah:'SMA 71 JKT',
    ptn:'UI',
    jurusan:'T.Mesin',
  },
  {
    nama:'Fitri Rizki Azzahra',
    asalSekolah:'SMAN 71 JKT',
    ptn:'UI',
    jurusan:'Administrasi Negara',
  },
  {
    nama:'Rivalezka Noer Nabilla',
    asalSekolah:'SMAN 71 JKT',
    ptn:'UI',
    jurusan:'T.Elektro',
  },
  {
    nama:'Inggita Mawarini Hamidah',
    asalSekolah:'SMAN 50 JKT',
    ptn:'UI',
    jurusan:'T.Lingkungan',
  },
  {
    nama:'Davina Salsabila',
    asalSekolah:'SMAN 110 JKT',
    ptn:'UI',
    jurusan:'Kesehatan & Keselamatan Kerja',
  },
  {
    nama:'Aisy Mecca Aprilistya',
    asalSekolah:'SMAN 52 JKT',
    ptn:'UI',
    jurusan:'Periklanan Kreatif',
  },

]